### PR TITLE
OUT-590 Initials in avatar in some places are a bit off

### PR DESCRIPTION
**Pull request by arpandhakal**
### Tasks

- [Initials in avatar in some places are a bit off](https://linear.app/copilotplatforms/issue/OUT-590/initials-in-avatar-in-some-places-are-a-bit-off)

### Changes

- [x] changed default fontsize of copilot avatar 
- [x] changed fontsize for selector button's starticon and sidebar props assignee selector. 

### Testing Criteria

- [LOOM](https://www.loom.com/share/95f49bbe0aa547e792180d809c1e44a2)

### CODE REVIEW

**Review by aatbip — CHANGES_REQUESTED** [review]
Avatar looks very small. It doesn't match with the Figma design - 

Screenshot from 2024-07-17 14-10-56

**Comment by rrojan** [comment]
image
This is too small for a user to use comfortably, please refer to the figma design for proper dimensions

**Review by rrojan — APPROVED** [review]
LGTM :trophy:

**Review by aatbip — CHANGES_REQUESTED** [review]
It still appears off on my side on the new task form. 

From new task form - 
Screenshot from 2024-07-23 16-03-43

As you can see above the letter 'A' looks off. It appears to be find on the sidebar though - 

From sidebar - 
Screenshot from 2024-07-23 16-05-45

**Review by aatbip — APPROVED** [review]
awesome work of art!

**Pull request merged**
