### PR TITLE
OUT-458 Design Polish

### PR DESCRIPTION
**Pull request by arpandhakal**
### Tasks

- [Design Polish](https://linear.app/copilotplatforms/issue/OUT-458/design-polish)
- [Task count color and size doesn't match design](https://linear.app/copilotplatforms/issue/OUT-464/task-count-color-and-size-doesnt-match-design)
- [Assignee and task label text color does not match design](https://linear.app/copilotplatforms/issue/OUT-461/assignee-and-task-label-text-color-does-not-match-design)
- [Board view + list view: General spacing issues](https://linear.app/copilotplatforms/issue/OUT-463/board-view-list-view-general-spacing-issues)
- [Task Workflow State row in List view extends to edges of app giving it a depth effect](https://linear.app/copilotplatforms/issue/OUT-467/task-workflow-state-row-in-list-view-extends-to-edges-of-app-giving-it)
- [Implement Due dates in task board + list view](https://linear.app/copilotplatforms/issue/OUT-462/implement-due-dates-in-task-board-list-view)

### Changes

- [x] fixed Assignee and task label text color does not match design.
- [x] Implemented Due dates in task board + list view.
- [x] Task Workflow State row in List view extends to edges.
- [x] changed bodySm in theme, which didnt quite align with the design system in figma.
- [x] fixed Board view + list view : General spacing issues.
- [x] added values equivalent to figma properties until a proper design system is provided.
- [x] Task count color and size doesn't match design.

### Testing Criteria

- [LOOM](https://www.loom.com/share/a939456e23ea4497bf2800b2d1e933cb)

### CODE REVIEW

**Review by rrojan — CHANGES_REQUESTED** [review]
OUT-467 seems to be incomplete still

image

(I embedded the preview link to iframe)

**Comment by aatbip** [comment]
> OUT-467 seems to be incomplete still
> 
> image
> 
> (I embedded the preview link to iframe)

I think this has been fixed in #99. Please check if that is what we are looking for. 
@arpandhakal @rrojan

**Comment by rrojan** [comment]
> > OUT-467 seems to be incomplete still
> > image
> > (I embedded the preview link to iframe)
> 
> I think this has been fixed in #99. Please check if that is what we are looking for. @arpandhakal @rrojan

@aatbip Sorry if the task title was not clear - the task is to extend the box holding the "Todo", "In progress", etc workflow states *to the edges of the viewport*. Please refer to the figma screenshot in the task to notice the changes.

Also there doesn't seem to be any padding on these workflow states which makes it look very cramped. I'm not sure if there is a task for this but that is a design discrepancy too.

**Review by rrojan — APPROVED** [review]
LGTM :trophy:

**Pull request merged**
