### PR TITLE
OUT-482 | Consistent avatar styling

### PR DESCRIPTION
**Pull request by rrojan**
### Tasks

- [OUT-482 | Consistent avatar styling](https://linear.app/copilotplatforms/issue/OUT-482/consistent-avatar-styling)

### Changes

- [x] Created a custom reusable CopilotAvatar component that takes fallbackColor for client & company into consideration
- [x] Change font size of initial letter following the design of copilot internal apps
- [x] Implement CopilotAvatar for IU board + list and cilent list view

### Testing Criteria
- [x] [LOOM](https://www.loom.com/share/67c194e260e743b0b42e42dd9ce92233?sid=e93a219c-b50f-463f-9c70-7b09767ef4c4)

### CODE REVIEW

**Review by aatbip — CHANGES_REQUESTED** [review]
Currently we are using the `CopilotAvatar` in the `**Card` components only but there are other places as well where the avatar component is being used in the older fashion. Can we employ this new `CopilotAvatar` component throughout the app where `Avatar` is being used? The places include `Selector` components and others IMO.

**Comment by rrojan** [comment]
> Currently we are using the `CopilotAvatar` in the `**Card` components only but there are other places as well where the avatar component is being used in the older fashion. Can we employ this new `CopilotAvatar` component throughout the app where `Avatar` is being used? The places include `Selector` components and others IMO.
> 
> Also, I think it is better if users can also pass some of the props from `AvatarProps` interface like width and height through the `CopilotAvatar` component, although default can be `20px`.

@aatbip regarding this, I split the replacing of remaining "Avatar" uses to another task (OUT-520) because of the potential for conficts with other assignee selector tasks at the moment. Will tackle that later when that branch is merged :raised_hands: 

Also, applied the suggested width prop fix for now

**Review by aatbip — APPROVED** [review]
lgtm

**Review by aatbip — DISMISSED** [review]

**Comment by rrojan** [comment]
Closing because a Re PR for this has been merged

**Pull request closed without merging**
