### PR TITLE
OUT-734 Hide sensitive error messages from production

### PR DESCRIPTION
**Pull request by arpandhakal**
### Tasks

- [Hide sensitive error messages from production](https://linear.app/copilotplatforms/issue/OUT-734/hide-sensitive-error-messages-from-production)

### Changes

- [x] added a condition to hide error message other than tokenError message in the error suspense component

### Testing Criteria

- [LOOM](https://www.loom.com/share/c3e0e3f23e1f43c0a5cdc3a9a93078b1)

### Notes

- In the loom video, I first created a fetch failed error by inserting random string in VERCEL_ENV variable, and for the second time I changed the VERCEL_ENV variable to 'production' which still causes fetch failed error locally, but the error is masked here.

### CODE REVIEW

**Review by aatbip — CHANGES_REQUESTED** [review]
I think it is a good idea to make a way for users to reset from the error states. Can we add a `reset` prop on this component and a button to initiate the `reset` that is available in the error components?

**Comment by rrojan** [comment]
> I think it is a good idea to make a way for users to reset from the error states. Can we add a `reset` prop on this component and a button to initiate the `reset` that is available in the error components?

Yeah, a "Try again" type of button would make sense.

**Review by rrojan — APPROVED** [review]
LGTM :trophy:

**Review by aatbip — APPROVED** [review]
lgtm

**Pull request merged**
